name: Deploy to AWS S3
on:
  push:
    branches:
      - main
jobs:
# 작업의 이름 지정
  build-and-depoly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: npm install
      working-directory: ./
      run: npm install
    - name: ckeditor add
      working-directory: ./
      run: npm add file:./ckeditor5
    - name: npm run build
      working-directory: ./
      run: npm run build
    - name: setup aws cli
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: "ap-northeast-2"
    - name: deploy to s3
      run: |
        aws s3 cp ./dist s3://logeat-bucket/ --recursive
